# Site settings
title: The Handsome Devils
email: glenrhodges@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official website for the most rockin, badass, hootin' and hollerin', drinkin', fightin', lovin' band of sons of bitches know The Handsome Devils.
baseurl: "/thd"
url: "thehandsomedevils.ca" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
