# Site settings
title: The Handsome Devils
email: glenrhodges@gmail.com
description: The official website for the most rockin’, badass, hootin’, hollerin’, drinkin’, fightin’, lovin’ sons o’ bitches known as The Handsome Devils.
url: "https://skinnard.github.io/thd"

# Build settings
markdown: kramdown

collections:
  - gigs
  - pictures
  - videos

timezone: America/New_York