# Site settings
title: The Handsome Devils
email: glenrhodges@gmail.com
description: > The official website for the most rockin, badass, hootin' and hollerin', drinkin', fightin', lovin' band of sons of bitches know The Handsome Devils.
baseurl: "/thd"
url: "thehandsomedevils.ca"


# Build settings
markdown: kramdown
